/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/laptop.glb
Author: 3D Y.A. (https://sketchfab.com/yamim)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-laptop-with-surface-keyboard-8ee705eccf814fc79df830e4f3aca01e
Title: Gaming Laptop With Surface Keyboard
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/laptop.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.11, 0, 0.13]} rotation={[-Math.PI / 2, 0, -1.28]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Material} scale={[1, 1, 1.41]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials['Material.003']} position={[-1.16, 0.86, 0]} rotation={[Math.PI / 2, 0.2, -Math.PI / 2]} scale={[1, 0.99, 0.99]} />
          <mesh geometry={nodes.Object_8.geometry} material={materials['Material.004']} position={[-0.13, 0.08, -0.01]} />
          <mesh geometry={nodes.Object_10.geometry} material={materials['Material.004']} position={[-0.69, 0.08, 0.09]} />
          <mesh geometry={nodes.Object_12.geometry} material={materials['Material.004']} position={[0.74, 0.07, 0]} scale={[1.07, 0.7, 1]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials['Material.002']} position={[0, 0.06, 0]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.46, 1.02, 1]} />
          <mesh geometry={nodes.Object_16.geometry} material={materials['Material.005']} position={[-1.15, 0.86, 0.06]} rotation={[Math.PI / 2, 0.2, -Math.PI / 2]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/laptop.glb')
