/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/mail.glb
Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mail-icon-b9133b28050d43aeb973aa0f08f86441
Title: Mail Icon
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Mail(props) {
  const { nodes, materials } = useGLTF("../../public/models/mail.glb");
  return (
    <group {...props} scale={[0.07, 0.07, 0.07]} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials["Material.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../../public/models/mail.glb");
